---
title: "power_logistic"
author: "Paul A. Bloom"
date: "2023-08-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
source('powersim_functions.R')
```

# Aim 1B

```{r}
iter = 100
start_time = Sys.time()
xh = c()
for (effsize in seq(from = -0.2, to = -0.01, by = .01)){
    print(effsize)
    for (i in 1:iter){
        print(i)
        xh = c(xh, simulate_study(effect_size_negative = effsize, effect_size_dose = 0, iter = i, param = 'time'))
    }
}

df <- do.call("rbind", xh)
write.csv(df, file = 'power_analysis_endorsement_aim_1b.csv', row.names = FALSE)
end_time = Sys.time()
print(start_time -end_time)
```


<!-- ```{r} -->
<!-- power_df = df %>% -->
<!--   dplyr::filter(term %in% c('conditionpos:time')) %>% -->
<!--   group_by(true_effect_size, term) %>% -->
<!--   summarise(n_sig = sum(`Pr...z..`<.05), -->
<!--             prop_sig = n_sig/n()) -->


<!-- ggplot(power_df, aes(x = -1*true_effect_size, y = prop_sig)) + -->
<!--   geom_line() + -->
<!--   geom_point() +  -->
<!--   geom_hline(yintercept = 0.8, lty = 2) + -->
<!--   labs(x = 'Valence X Time Effect Size\nMean pre > post decrease in proportion endorsement of negative words as self-referential\nAssuming no change in proportion endorsement of positive words as self-referential', -->
<!--        y = 'Power') -->
<!-- ``` -->