---
title: "power_logistic"
author: "Paul A. Bloom"
date: "2023-08-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
source('powersim_functions.R')
```

# Aim 2B

```{r}
iter = 100
start_time = Sys.time()
xh = c()
for (effsize in seq(from = -0.2, to = -0.01, by = .01)){
    print(effsize)
    for (i in 1:iter){
        print(i)
        xh = c(xh, simulate_study(effect_size_negative = -0.025, effect_size_dose = effsize, iter = i, param = 'time:dose'))
    }
}

df <- do.call("rbind", xh)
write.csv(df, file = 'power_analysis_endorsement_aim_2b.csv', row.names = FALSE)
end_time = Sys.time()
print(start_time -end_time)
```


```{r}
df_1b = read_csv('power_analysis_endorsement_aim_1b.csv') %>%
  mutate(type = 'Aim 1B') %>%
  dplyr::filter(term %in% c('conditionpos:time')) 

df_2b = read_csv('power_analysis_endorsement_aim_2b.csv') %>%
  mutate(type = 'Aim 2B') %>%
  dplyr::filter(term %in% c('conditionpos:time:group30')) 

df = rbind(df_1b, df_2b)
```

```{r}
power_df = df %>%
  #dplyr::filter(term %in% c('conditionpos:time')) %>%
  group_by(true_effect_size, term, type) %>%
  summarise(n_sig = sum(`Pr...z..`<.05),
            prop_sig = n_sig/n())


ggplot(power_df, aes(x = -1*true_effect_size, y = prop_sig, color = type)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.8, lty = 2) +
  labs(x = 'Effect Size\nChange in Proportion of Negative Words Endorsed',
       y = 'Power')
```